---
- name: User Mgm
  hosts: all 
  tasks: 
  - name: New user adding  playbook
    user:
     name: nick               
     comment: delete user  
     shell: /bin/bash         
     group: QA,nick
     state: absent 
     remove: yes                

  
