---
- name: Setup Apache, user, and firewall
  hosts: all
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true
      tags: ins_apache

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: true
      tags: apache_start

    - name: Create test_user
      user:
        name: test_user
        shell: /bin/bash
        state: present
      tags: user

    - name: Allow HTTP traffic through UFW
      ufw:
        rule: allow
        name: "Apache Full"
      tags: firewall

    - name: Enable UFW
      ufw:
        state: enabled
      tags: firewall

